### ISSUE TITLE
Make Jupyter-aware with _repr_html_()

### ISSUE THREAD

**Issue by flutefreak7** [jazzband/prettytable#127]
### Is your feature request related to a problem? Please describe.

When using PrettyTable in Jupyter Notebooks, print(table) produces the ASCII table which is inferior to an HTML representation like pandas and other notebook-friendly libraries use.

A pedantic solution to using the HTML output would be:

```python
from IPython.display import HTML, display

display(HTML(table.get_html_string()))
```

But giving PrettyTable a proper `_repr_html_()` works much better: `PrettyTable._repr_html_ = PrettyTable.`

![image](https://user-images.githubusercontent.com/2966015/133335468-53096a40-2f56-426d-9686-2d09fb1bb82d.png)

### Describe the solution you'd like

PrettyTable should have a `_repr_html_()` which calls `self.get_html_string()` so that it is a Jupyter-aware table.
PrettyTable should also have a basic `__repr__()` method returning the same as `__str__()` while we're at it. Not having a `repr` at all seems pretty lacking compared to most mature libraries.

**Comment by hugovk** [comment]
How does PR https://github.com/jazzband/prettytable/pull/146 look?

**Comment by flutefreak7** [comment]
> 
> 
> How does PR #146 look?

Looks good to me! I think Jupyter users will appreciate this easy win for improved usability.
