### ISSUE TITLE
PrettyTable should expose its data for consumption by other table libraries

### ISSUE THREAD

**Issue by flutefreak7** [jazzband/prettytable#128]
### Is your feature request related to a problem? Please describe.

If I construct a PrettyTable, it's only useful for display... it's a dead end... if I want to then use it with other libraries (like pandas, matplotlib, openpyxl, etc), I have no way to access a PrettyTable's data via the public API.

### Describe the solution you'd like

I'd like if there was a `rows` or `data` attribute exposed publicly so that the table could be an input to downstream functions.

### Describe alternatives you've considered

Accessing the `table._rows` "hidden" attribute works fine, it just means I'm relying on a private implementation detail instead of a part of the API.

`df = pd.DataFrame(table._rows, columns=table.field_names)` works fine and is what I'm currently using.

**Comment by hugovk** [comment]
Sounds reasonable, although I think getter methods would be preferable, to avoid the impression that you can set data like `table.rows = ...`, to make sure adding data goes through validation.

**Comment by hugovk** [comment]
How does PR https://github.com/jazzband/prettytable/pull/147 look?
