### ISSUE TITLE
Some ansi-escape sequences break width

### ISSUE THREAD

**Issue by hydrargyrum** [jazzband/prettytable#129]
### What did you do?

`blessed` is a popular python library for dealing with terminal escape codes. I use it for coloring.
However prettytable doesn't interpret some codes correctly.

### What did you expect to happen?

The color codes are interpreted fine by prettytable as 0-width and so should the color-reset code.

### What actually happened?

The color codes are interpreted fine by prettytable as 0-width but not the color-reset code which thus breaks the width as the terminal renders 0-width but prettytable accounted multiple characters width.

### What versions are you using?

* Python: 3.9
* PrettyTable: prettytable==2.2.0 (and same problem though different rendering with debian's prettytable==0.7.2)

Please include **code** that reproduces the issue.

```python
import prettytable

tab = prettytable.PrettyTable(["foo", "bar"])
tab.add_row([1, 2])
tab.add_row([3, 4])
print(tab)  # everything fine so far

import blessed
t = blessed.Terminal()
tab.add_row([f"{t.bold_red}{t.bold_red}{t.bold_red}{t.bold_red}1", "2"])
print(tab)  # width is ok, color is not finished but that's my fault, no bug here

tab.add_row([f"{t.normal}{t.normal}{t.normal}{t.normal}1", "2"])
print(tab)  # now cell width is broken!
```

**Comment by hugovk** [comment]
The problem is here:

https://github.com/jazzband/prettytable/blob/0a8f5b92f91064a662ff68f016deb26e24e0c5e5/src/prettytable/prettytable.py#L62

https://github.com/jazzband/prettytable/blob/0a8f5b92f91064a662ff68f016deb26e24e0c5e5/src/prettytable/prettytable.py#L2049-L2050

The regex is stripping the colour codes, but not the reset code.

Colour codes match:

```pycon
>>> import re, blessed
>>> _re = re.compile(r"\033\[[0-9;]*m")
>>> t = blessed.Terminal()
>>>
>>> "\x1b" == "\033"
True
>>>
>>> t.bold_red
'\x1b[1m\x1b[31m'
>>> _re.sub("", f"**{t.bold_red}**")
'****'
>>> t.blue
'\x1b[34m'
>>> _re.sub("", f"**{t.blue}**")
'****'
```

But not the whole reset code:

```pycon
>>> t.normal
'\x1b(B\x1b[m'
>>> _re.sub("", f"**{t.normal}**")
'**\x1b(B**'
```

We could remove that reset code:

```diff
 def _str_block_width(val):
+    val = val.replace("\x1b(B\x1b[m", "")
     return wcwidth.wcswidth(_re.sub("", val))
```

![image](https://user-images.githubusercontent.com/1324225/134326086-90458b12-c73c-445c-b4d4-3ac471ed138d.png)

There's probably some other cases not covered by hardcoding this as a constant, like the code being different for different terminals or languages, but this will probably cover many common ones quickly.

What do you think?

**Comment by hydrargyrum** [comment]
Be careful with that reset code, there are actually 2 reset code in blessed's `normal`:
- `\x1b[m` which is [SGR reset](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR) (alternate form: `\x1b[0m`). This is commonly found in libs like [colorama](https://github.com/tartley/colorama/blob/master/colorama/ansi.py) or [randomly found](https://gist.github.com/rene-d/9e584a7dd2935d0f461904b9f2950007) hand-written formatting
- `\x1b(B`, which is much more rare, is [`set0_des_seq`](https://github.com/jquast/blessed/blob/2d75fdc38fc98706d19256df5bf0b250a659ac79/blessed/_capabilities.py#L111) for *Shift to codeset 0 (EUC set 0, ASCII)* according to `terminfo(5)`. I'm not sure what's its exact purpose.

The 2 codes might not always be in that order, one of them could be missing (especially the `set0_des_seq` one). They should be treated separately IMHO, not as a whole, each one having 0-width.

(The `sgr0` terminfo variable of my terminal contains both:
```
% echo $terminfo[sgr0] | vhd
1B (  B  1B [  m  \n
```
)

**Comment by hugovk** [comment]
For `\x1b(B`, https://stackoverflow.com/a/36280289/724176 quotes from https://invisible-island.net/xterm/ctlseqs/ctlseqs.html:

```
ESC ( C   Designate G0 Character Set (ISO 2022, VT100).
          Final character C for designating 94-character sets.  In this
          list, 0 , A  and B  apply to VT100 and up, the remainder to
          VT220 and up.  The VT220 character sets, together with the
          Portuguese character set are activated by the National
          Replacement Character controls.  The A  is a special case,
          since it is also activated by the VT300-control for British
          Latin-1 separately from the National Replacement Character
          controls.
    ...
            C = B  -> United States (USASCII).
```

In full and since revised as:


```
ESC ( C   Designate G0 Character Set, VT100, ISO 2022.
          Final character C for designating 94-character sets.  In this
          list,
          o   0 , A  and B  were introduced in the VT100,
          o   most were introduced in the VT200 series,
          o   a few were introduced in the VT300 series, and
          o   a few more were introduced in the VT500 series.
          The VT220 character sets, together with a few others (such as
          Portuguese) are activated by the National Replacement
          Character Set (NRCS) controls.  The term "replacement" says
          that the character set is formed by replacing some of the
          characters in a set (termed the Multinational Character Set)
          with more useful ones for a given language.  The ASCII and DEC
          Supplemental character sets make up the two halves of the
          Multinational Character set, initially mapped to GL and GR.
          The valid final characters C for this control are:
            C = A  ⇒  United Kingdom (UK), VT100.
            C = B  ⇒  United States (USASCII), VT100.
            C = C  or 5  ⇒  Finnish, VT200.
            C = H  or 7  ⇒  Swedish, VT200.
            C = K  ⇒  German, VT200.
            C = Q  or 9  ⇒  French Canadian, VT200.
            C = R  or f  ⇒  French, VT200.
            C = Y  ⇒  Italian, VT200.
            C = Z  ⇒  Spanish, VT200.
            C = 4  ⇒  Dutch, VT200.
            C = " >  ⇒  Greek, VT500.
            C = % 2  ⇒  Turkish, VT500.
            C = % 6  ⇒  Portuguese, VT300.
            C = % =  ⇒  Hebrew, VT500.
            C = =  ⇒  Swiss, VT200.
            C = ` , E  or 6  ⇒  Norwegian/Danish, VT200.
          The final character A  is a special case, since the same final
          character is used by the VT300-control for the 96-character
          British Latin-1.
          There are a few other 94-character sets:
            C = 0  ⇒  DEC Special Character and Line Drawing Set, VT100.
            C = <  ⇒  DEC Supplemental, VT200.
            C = >  ⇒  DEC Technical, VT300.
          These are documented as 94-character sets (like USASCII)
          without NRCS:
            C = " 4  ⇒  DEC Hebrew, VT500.
            C = " ?  ⇒  DEC Greek, VT500.
            C = % 0  ⇒  DEC Turkish, VT500.
            C = % 5  ⇒  DEC Supplemental Graphics, VT300.
            C = & 4  ⇒  DEC Cyrillic, VT500.
          The VT520 reference manual lists a few more, but no
          documentation has been found for the mappings:
            C = % 3  ⇒  SCS NRCS, VT500.
            C = & 5  ⇒  DEC Russian, VT500.
```


The regex is already stripping `\x1b[m`, so how about this?

```diff
 def _str_block_width(val):
+    val = val.replace("\x1b(B", "")
     return wcwidth.wcswidth(_re.sub("", val))
```

That should cover at least blessed users (680k downloads per month).

How common do you think other language codes are? Do you think it's worth covering some/all of those?

**Comment by hydrargyrum** [comment]
After a quick tour of some libraries (among which colorama, termcolor, rich, fabulous and some more), most fall in the basic cases. However, [colored](https://gitlab.com/dslackw/colored) seems to include `\x01` (start of heading) and `\x02` (start of text) for "interactive" use, not sure what it means.

```
In [96]: colored.stylize("foo", colored.fg("red"))
Out[96]: '\x1b[38;5;1mfoo\x1b[0m'

In [97]: colored.stylize_interactive("foo", colored.fg("red"))
Out[97]: '\x01\x1b[38;5;1m\x02foo\x01\x1b[0m\x02'
```

Perhaps it could be skipped too by prettytable. Apart from that, we may be good.

**Comment by hugovk** [comment]
Thanks for reviewing the other libraries!

For comparison:

<table>
<tr>
	<th>library
	<th>PyPI downloads in August
<tr>
<tr>
	<td>colorama
	<td align="right">95,607,480
<tr>
	<td>termcolor
	<td align="right">11,758,645
<tr>
	<td>rich
	<td align="right">2,087,658
<tr>
	<td>blessed
	<td align="right">680,081
<tr>
	<td>fabulous
	<td align="right">1,173
</table>


Your proposal sounds good, would you like to create a PR? Unit tests would be helpful to avoid future regressions.
