### ISSUE TITLE
Wrap strings to newline when maximum width of column is reached

### ISSUE THREAD

**Issue by sgrontflix** [jazzband/prettytable#130]
When a string is too long, the generated table breaks (like in issue #89)
It would be nice to add a maximum width for all or certain columns and when that width is reached, the string automatically wraps to newline.

For example:

```
+--------+------------------------+-----------+
| ChatID | Word                   | Timestamp |
+--------+------------------------+-----------+
| aaa    | bbbbbbbbbbbbbbbbbbbbbb | ccc       |
| ddd    | eee                    | fff       |
| ggg    | hhh                    | iii       |
+--------+------------------------+-----------+
```

should turn into this:

```
+--------+------------+-----------+
| ChatID | Word       | Timestamp |
+--------+------------+-----------+
| aaa    | bbbbbbbbbb | ccc       |
|        | bbbbbbbbbb |           |
|        | bb         |           |
| ddd    | eee        | fff       |
| ggg    | hhh        | iii       |
+--------+------------+-----------+
```

I have considered using the `textwrap` module to achieve this behavior:
`tuples = [('aaa', textwrap.fill('bbbbbbbbbbbbbbbbbbbbbb', 10), 'ccc'), ('ddd', 'eee', 'fff'), ('ggg', 'hhh', 'iii')]`

---

EDIT: After digging into the code, I found the [max_width](https://github.com/jazzband/prettytable/blob/0a8f5b92f91064a662ff68f016deb26e24e0c5e5/src/prettytable/prettytable.py#L599) property, which achieves exactly what I described above. Thank you anyway!

Example:
```python
from prettytable import PrettyTable


tuples = [('aaa', 'bbbbbbbbbbbbbbbbbbbbbb', 'ccc'), ('ddd', 'eee', 'fff'), ('ggg', 'hhh', 'iii')]

t = PrettyTable(['Col 1', 'Col 2', 'Col 3'], align='l', max_width=10)
t.add_rows(tuples)

print(t)
```

**Comment by hugovk** [comment]
These were documented in the docstrings in https://github.com/jazzband/prettytable/pull/98/files but not the README. PR welcome to add to the README too.

**Comment by RyanCigich** [comment]
Am I missing something in the max_length that prevents it from wrapping headers as well?

![image](https://github.com/jazzband/prettytable/assets/108053282/f80a2d68-92e5-4280-a51f-5a2d3763a1f8)

Also, should max_table_width wrap the title?

![image](https://github.com/jazzband/prettytable/assets/108053282/1bb967ea-fcd9-4a5c-a73e-cf30b99e0c69)

After commenting, I also noticed that the max_width for '1' is 20 in both tables, but in the 2 tables the wrapping for that column is not the same.  Is that intended?

I'm trying to setup constraints that will keep the table within 100 characters wide and will accommodate any title length.  I had assumed that PrettyTable would handle this automagically after I set the min/max widths.  I'm not getting what I expected from the header, and I am extrapolating an assumption about the title and max_table_width.

**Comment by anibal2j** [comment]
I have the same issue as the previous comment. My headers are not wrapping. Shouldn't the max_width apply to the headers as well as the contents of the table? is there a workaround?

**Comment by hugovk** [comment]
Please could you test with latest `main` in case https://github.com/jazzband/prettytable/pull/289 helps, and if not, please open a new issue with a minimal example to reproduce?

**Comment by anibal2j** [comment]
I upgraded to 3.10.0 and I'm getting this error:

```pytb
Anibals-New-Air:VMG anibal$ python3 jjj.py
Traceback (most recent call last):
  File "/Users/anibal/PycharmProjects/VMG/jjj.py", line 6, in <module>
    print(x.get_string())
  File "/Users/anibal/.pyenv/versions/3.9.16/lib/python3.9/site-packages/prettytable/prettytable.py", line 1798, in get_string
    self._stringify_row(
  File "/Users/anibal/.pyenv/versions/3.9.16/lib/python3.9/site-packages/prettytable/prettytable.py", line 1959, in _stringify_row
    line = textwrap.fill(line, width)
  File "/Users/anibal/.pyenv/versions/3.9.16/lib/python3.9/textwrap.py", line 391, in fill
    return w.fill(text)
  File "/Users/anibal/.pyenv/versions/3.9.16/lib/python3.9/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/Users/anibal/.pyenv/versions/3.9.16/lib/python3.9/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/Users/anibal/.pyenv/versions/3.9.16/lib/python3.9/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```

The code is simply this:

```python
from prettytable import PrettyTable

x = PrettyTable(max_table_width=10)
x.field_names = ["MRN", "Acc Number", "Timestamp", "HL7 sending facility/calling AE"]
x.add_row(['short', 'very long that will wrap after 10 chars', 'Short', 'Short'])
print(x.get_string())

```

**Comment by anibal2j** [comment]
Tried with python 3.11 and getting the same thing as well.

**Comment by hugovk** [comment]
It's working with latest unreleased `main`, which contains #289:

```
+---+---+---+---+
| M | A | T | H |
+---+---+---+---+
| s | v | S | S |
| h | e | h | h |
| o | r | o | o |
| r | y | r | r |
| t | l | t | t |
|   | o |   |   |
|   | n |   |   |
|   | g |   |   |
|   | t |   |   |
|   | h |   |   |
|   | a |   |   |
|   | t |   |   |
|   | w |   |   |
|   | i |   |   |
|   | l |   |   |
|   | l |   |   |
|   | w |   |   |
|   | r |   |   |
|   | a |   |   |
|   | p |   |   |
|   | a |   |   |
|   | f |   |   |
|   | t |   |   |
|   | e |   |   |
|   | r |   |   |
|   | 1 |   |   |
|   | 0 |   |   |
|   | c |   |   |
|   | h |   |   |
|   | a |   |   |
|   | r |   |   |
|   | s |   |   |
+---+---+---+---+
```

I'll make a new release soon.

**Comment by anibal2j** [comment]
Once the new version is out let me know and I'll try it with my production code

**Comment by anibal2j** [comment]
Is there a new release with this fix?

**Comment by hugovk** [comment]
Yes it was released in https://github.com/jazzband/prettytable/releases/tag/3.10.1

**Comment by anibal2j** [comment]
hmm, I'm getting this:

```
ERROR: Could not find a version that satisfies the requirement pretty_table==3.10.1 (from versions: none)
ERROR: No matching distribution found for pretty_table==3.10.1
```

**Comment by hugovk** [comment]
It's prettytable, not pretty_table.

**Comment by anibal2j** [comment]
I just tried the new version and it's still not wrapping the headers. It's wrapping the contents of each row, but not the header itself. I'm using 3.10.2.

**Comment by hugovk** [comment]
Yes, I see: https://github.com/jazzband/prettytable/issues/130#issuecomment-2031187494.

PR welcome to fix this.
