### ISSUE TITLE
Add a get_latex_string() method 

### ISSUE THREAD

**Issue by kinianlo** [jazzband/prettytable#131]
### Is your feature request related to a problem? Please describe.

Unable to get code that produces the table in LaTex.

### Describe the solution you'd like

Add a get_latex_string() method that returns latex code which reproduces the table in LaTex. Should be very similar to the get_html_string() method.

### Describe alternatives you've considered

Get string in Markdown format and translate them into latex code using other tools, eg [https://tableconvert.com/](https://tableconvert.com/). 

### Additional context
The prettytable counterpart in Julia has the desired feature:
[https://ronisbr.github.io/PrettyTables.jl/stable/man/latex_backend/](https://ronisbr.github.io/PrettyTables.jl/stable/man/latex_backend/)

**Comment by hugovk** [comment]
PR welcome!
