### ISSUE TITLE
Unused Argument in _format_row

### ISSUE THREAD

**Issue by Sarath191181208** [jazzband/prettytable#137]
### This isn't a big problem but,

I had just found a unused argument 'options' in implementation of _format_rows.
I thought to let you guys know that. If this is already reported I am really sorry, you see I am pretty new to this stuff.

### Describe the solution you'd like

There are a six locations of the format row implementation . I don't know if this is even helpful . I am guessing that it is there to add a new feature. If that's the case I am really sorry.

**Comment by hugovk** [comment]
Thanks for the report!

It's been there a long time:

![image](https://user-images.githubusercontent.com/1324225/136704093-2c349c2b-61cc-4d62-9434-9f2a8256d444.png)

https://github.com/jazzband/prettytable/blame/4862c815ed2d2bc2931dd2b6324b84158c3e9b8b/prettytable.py#L1113-L1117

I don't know the original intent, perhaps it was in case some of the `options` would be needed further along. But it's not needed now, so it looks safe to remove `options` from both `_format_rows` and `_format_rows`, they're both private methods.

Would you like to submit a PR?

**Comment by Sarath191181208** [comment]
Yeah I thought that was the case but I wanted to tell anyways. I am new to github so I am not sure if can make a PR. I will try tough

**Comment by hugovk** [comment]
Great!

As this is a change in a single file, it can be done through the GitHub UI:

1. Go to https://github.com/jazzband/prettytable/blob/master/src/prettytable/prettytable.py
2. Click the pencil icon in the top right to edit the file
3. It'll say it's making a fork for you, you may need to select where to make the fork (choose your username)
4. Change the code: delete `options` from `_format_rows` and `_format_row`, and where they're called
5. Scroll down to the bottom, where it says "Commit changes"
6. Enter a short message (like "Remove unused options in _format_rows and _format_row"
7. Choose "Create a new branch for this commit and start a pull request"
8. You can give a name for the branch if you like, or "patch-1" is fine
9. Click "Propose changes"
10. It then opens a page for you to now create the PR
11. Leave the title and put "Fixes #137" in the description box. You can add more info here too.
12. Click to create the pull request!

More info: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

Feel free to ask questions!

**Comment by Sarath191181208** [comment]
I have done what you had told me thanks. Can you please tell me how to test my code

**Comment by hugovk** [comment]
We can see the tests running on the CI now: https://github.com/jazzband/prettytable/pull/138 (I had to approve for a first time contributor :)

**Comment by Sarath191181208** [comment]
Thanks

**Comment by Sarath191181208** [comment]
Shall I close it now?

**Comment by hugovk** [comment]
No, let's wait for the CI to finish running, it should all turn green soon. Then I'll review it and merge it.

**Comment by hugovk** [comment]
I merged your PR, thank you very much for your contribution! 🎈

**Comment by Sarath191181208** [comment]
I should thank you for showing me the ropes.

**Comment by hugovk** [comment]
You're very welcome!
