### ISSUE TITLE
ImportError: cannot import name '__version__' from partially initialized module 'prettytable' (most likely due to a circular import)

### ISSUE THREAD

**Issue by NaveenkumarMD** [jazzband/prettytable#154]
#### I was trying to use this prettytable module. When I import this prettytable using
```python
from prettytable import Prettytable
```
i got his error
![image](https://user-images.githubusercontent.com/72449129/144960024-ce20e26c-640c-41bb-afd0-5a86385d9f6c.png)

* OS: Windows
* Python: 3.8
* PrettyTable: 2.4.0

The code i have used
```python
from prettytable import Prettytable
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Student Name", "Class", "Section", "Percentage"])
  
```

**Comment by hugovk** [comment]
Two problems:

1. Do not call your own file `prettytable.py`, it's clashing with this library. Use `my_prettytable.py` or something else.

2. It's `PrettyTable` not `Prettytable`:

```diff
-from prettytable import Prettytable
+from prettytable import PrettyTable
```
