### ISSUE TITLE
2.5.0: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [jazzband/prettytable#156]
### What did you do?
I'm trying to package your module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.

### What did you expect to happen?
pytest should finish without errors or failutes.

### What actually happened?
pytest is failing.

### What versions are you using?
* OS: Linux x86/64
* Python: 3.8.12
* PrettyTable: 2.5.0
* pytest: 6.2.5

Please include **code** that reproduces the issue.
- `python3 -sBm build -w`
- install .whl file in </install/prefix>
- run pytest with PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>

pytest oputput:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-prettytable-2.5.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-prettytable-2.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/prettytable-2.5.0
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
________________________________________________________________ ERROR collecting tests/test_prettytable.py ________________________________________________________________
tests/test_prettytable.py:97: in <module>
    class TestBuildEquivalence:
tests/test_prettytable.py:105: in TestBuildEquivalence
    pytest.lazy_fixture("row_prettytable"),
E   AttributeError: module 'pytest' has no attribute 'lazy_fixture'
========================================================================= short test summary info ==========================================================================
ERROR tests/test_prettytable.py - AttributeError: module 'pytest' has no attribute 'lazy_fixture'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.40s =============================================================================
```

**Comment by hugovk** [comment]
Please test with tox (e.g. `tox -e py38`) or install with the `tests` extra (e.g. `pip install -e ".[tests]"`).

**Comment by kloczek** [comment]
Thx for the hint with `[tests]` dependencies.
I think that you should add `wcwidth` to that set of modules.
After installing missing `pytest-lazy-fixture` pytest is OK (as I'm building package in isolated env I do need yet another layer of isol;arion on form of venv)
Using pytest instead tox has more sense because it allows make test build against unspecivied in `[tests]` pytest extensions which may show some additional issue depends on those installed sdditiona extensions lik for example test ttest suite using `pytest-random` to check is there any order dependencies between test suite units.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-prettytable-2.5.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-prettytable-2.5.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/prettytable-2.5.0
plugins: cov-3.0.0, lazy-fixture-0.6.3
collected 109 items

tests/test_prettytable.py .............................................................................................................                              [100%]

=========================================================================== 109 passed in 0.51s ============================================================================
```

**Comment by hugovk** [comment]
We don't need to add wcwidth to the `tests` extra, it's already in `install_requires`:

https://github.com/jazzband/prettytable/blob/508d0d42a45011a0ca12a92ffb39f68f16e9b03f/setup.cfg#L28-L30

In fact, tox runs pytest and installs the `tests` extra:
 https://github.com/jazzband/prettytable/blob/508d0d42a45011a0ca12a92ffb39f68f16e9b03f/tox.ini#L9-L10

But good you got it working with pytest directly, it can be quicker too.

**Comment by kloczek** [comment]
`wcwidth` is not needed on install stage.
However pytest is using that module.
