### ISSUE TITLE
use custom exception type

### ISSUE THREAD

**Issue by fawaf** [jazzband/prettytable#168]
### Is your feature request related to a problem? Please describe.
no

### Describe the solution you'd like

use a custom exception/error type so one does not have to catch all errors of type `Exception`

### Describe alternatives you've considered

A clear and concise description of any alternative solutions or features you've
considered.

**Comment by hugovk** [comment]
Good idea, `Exception` is too broad.

How about PR https://github.com/jazzband/prettytable/pull/169, which uses the familiar built-in exceptions (`IndexError`, `TypeError` and `ValueError`) instead of the `Exception` base class?

https://docs.python.org/3/library/exceptions.html
