### ISSUE TITLE
reset table without recreating object

### ISSUE THREAD

**Issue by fawaf** [jazzband/prettytable#175]
### Is your feature request related to a problem? Please describe.
no

### Describe the solution you'd like
support resetting the table without recreating a new object each time

### Describe alternatives you've considered
recreate a new object each time

### Additional context
```python
table = PrettyTable()
table.field_names = ["a","b"]
table.add_rows(["some", "thing"])

table.reset()
table.field_names = ["x","y"]
table.add_rows(["other", "thing"])
```

**Comment by hugovk** [comment]
Please could you say why a reset function is preferable to using a new object?

It's a one line difference to the end user, but it would need more code, tests and maintenance for PrettyTable.

Plus if I'm reading code, its clear to me what creating a new object will do, whereas calling a reset function is opaque: I don't know if it resets formatting only, data only, styles only, or everything.

**Comment by fawaf** [comment]
mainly not duplicating code of creating new objects all the time. it's more of a nice to have. the styles/formatting would have to be re-done each time the object is recreated.

i would likely expect the reset function to have a setting/arg to tell it what to reset. i could see it being useful when one wants to keep the formatting/styles the same but wants to reset the table for a bunch of different data.

**Comment by hadrielk** [comment]
> the styles/formatting would have to be re-done each time the object is recreated.

You can just write a single function that creates a table and sets the properties/options you want. Then the rest of your code just invokes that to "reset" the table whenever.

**Comment by hugovk** [comment]
That's a good approach, then you can reset data and retain styles/formatting exactly as you need.

Some people might be surprised that a reset function doesn't reset styles formatting.

Thanks for the issue, let's close.
