### ISSUE TITLE
Problem with termcolor + multi-line strings

### ISSUE THREAD

**Issue by resposit** [jazzband/prettytable#187]
Hello,

I tried to create a table having one cell containing a colored multi-line string (using "\n" ).
This seems to break the color of table borders.
For example:
```python
from prettytable import PrettyTable
from termcolor import colored
rows = [["A", colored("line1\nline2", 'red')]]
t = PrettyTable()
t.add_rows(rows)
print(t)
```
![multiline](https://user-images.githubusercontent.com/32873756/175502827-ea986430-cbab-4831-a72c-c6ce9e5488ef.png)

Everything is fine with a single-line colored string:

![singleline](https://user-images.githubusercontent.com/32873756/175503398-592a5e37-8a65-4650-a792-20a7377745c2.png)

Is it a bug/feature or is there a better way to do this ?
Thanks

**Comment by hugovk** [comment]
It's either a bug or not supported yet :)

A workaround is to apply the colour to the text before and after the newline, but not to the newline itself.

For example:

```python
from prettytable import PrettyTable
from termcolor import colored
rows2 = [["A", colored("line1", "red") + "\n" +colored("line2", "red")]]
t2 = PrettyTable()
t2.add_rows(rows2)
print(t2)
```

<img width="546" alt="image" src="https://user-images.githubusercontent.com/1324225/175826193-49a5cbc7-f538-43c6-9779-fe36b3965973.png">


Or with a helper:

```python
from prettytable import PrettyTable
from termcolor import colored


def multiline_colored(text, color):
    lines = text.split("\n")
    lines = [colored(line, color) for line in lines]
    return "\n".join(lines)


rows3 = [["A", multiline_colored("line1\nline2", "red")]]
t3 = PrettyTable()
t3.add_rows(rows3)
print(t3)
```

Which could also be:

```python
def multiline_colored(text, color):
    return "\n".join([colored(line, color) for line in text.split("\n")])
```

**Comment by resposit** [comment]
Thank you for the workaround, it works perfectly.
