### ISSUE TITLE
Add mypy via pre-commit and make mypy pass

### ISSUE THREAD

**Issue by phershbe** [jazzband/prettytable#206]
From issue: https://github.com/jazzband/prettytable/issues/203

My pull request from the issue above didn't include `Add mypy via pre-commit and make mypy pass` as we agreed that it was better to go little by little. I have no plans to let this slip through the cracks, but I wanted to create an issue here in order to be safe.

**Comment by hugovk** [comment]
Let's close this, thanks again for working on this :)
