### ISSUE TITLE
PyPI v3.5.0 doesnt have an sdist 

### ISSUE THREAD

**Issue by jayvdb** [jazzband/prettytable#214]
Previously https://pypi.org/project/prettytable/#files has contained an sdist.

For v3.5.0, there is only a wheel.

jazzband managed projects typically follow the convention of uploading an sdist.
Is that going to be a possibility with hitch?

**Comment by hugovk** [comment]
It's nothing to do with Hatchling. 

With Jazzband, release files go to a staging server on https://jazzband.co first, and it looks like I forgot to approve the upload of the sdist to PyPI. 

That's now done: https://pypi.org/project/prettytable/3.5.0/#files

Thanks for letting us know!
