### ISSUE TITLE
Can not align the  text   when the text is in  chinese.

### ISSUE THREAD

**Issue by longzhang** [jazzband/prettytable#222]
When I set the option  align  with  left ,  

`tb.align = "l"`

But it can not work when the text  in Chinese .

I thought maybe that's the  method of length return  is not support the  real width we looked.

For example,  In Chinese , The strings  like  "你好" return the length with 2, but it takes 4 width in in practical. 
In english , the  vocabulary width we saw is the same to the result of length method. 

![WX20221205-164703@2x](https://user-images.githubusercontent.com/2120788/205595897-72caf7b5-73f5-4fe0-8fa7-4cdf70bba278.png)

**Comment by hugovk** [comment]
Thanks for the report. Duplicate of https://github.com/jazzband/prettytable/issues/213, see also https://github.com/jazzband/prettytable/issues/49 for some suggestions. PRs welcome to improve this.

**Comment by longzhang** [comment]
Thank  U all .
It's so sad that it took my 3 hours to fix it.
The style is correct. 
Chinese font is  displayed abnormal in PyCharm. 
But it looks normal in iTerm.
