### ISSUE TITLE
How to save prettytable as csv or json file?

### ISSUE THREAD

**Issue by zxczrx123** [jazzband/prettytable#224]
Hi, thanks for your great work!

I want to know how to save prettytable as csv or json file elegantly？

**Comment by zxczrx123** [comment]
```python
import io
import csv
reader = csv.reader(io.StringIO(x.get_csv_string())) 
with open('string2csv.csv', 'w') as out_file:
    writer = csv.writer(out_file)
    writer.writerows(reader)
```

I have found a way. Is there a more concise io interface？

**Comment by hugovk** [comment]
That looks pretty good to me.

No, PrettyTable only does string output via the `get*_string` methods.

**Comment by ewyluda** [comment]
x.get_csv_string() no longer works... I've been using this method for 6 months or so without any issue, went to rerun my code today and i keep getting an attribute error... any suggestions? 
![image](https://user-images.githubusercontent.com/35318463/228329196-a89824de-8806-438b-bdc4-a7ff8d97cff9.png)

**Comment by hugovk** [comment]
@ewyluda Please open a new, detailed issue: https://github.com/jazzband/prettytable/issues/new/choose
