### ISSUE TITLE
Sending a prettytable by email using Outlook doesn't keep format

### ISSUE THREAD

**Issue by jifcon** [jazzband/prettytable#239]
Hi everyone!

I'm trying to send a prettytable as email in outlook (through win32com package) and the table loses it's format (I send it as string using get_string()). I guess that the problem is that it's not using monospace but I'm not sure if it can be fixed.

I tried several options like ljust, center, rjust, using a fixed string length for every element but nothing works.

Do you have an idea on how to fix this?

I saw several posts about this issue with chinese chars but not with latin chars.

Thanks++!

JI

![image](https://user-images.githubusercontent.com/38166748/232844988-6676157c-a7b4-4993-9c6b-3a4d2df96daf.png)

**Comment by hugovk** [comment]
Format it with a fixed-width font like Courier New.

But this is really a question for an Outlook forum, not PrettyTable :)
