### ISSUE TITLE
missing pypi source tarball for 3.8.0 release

### ISSUE THREAD

**Issue by chenrui333** [jazzband/prettytable#246]
👋 it looks like the pypi tarball file is missed for the 3.8.0 release, raise an issue in here for some awareness. Thanks!

**Comment by hugovk** [comment]
I'm not sure what went wrong, but I've now uploaded it: https://pypi.org/project/prettytable/3.8.0/#files

Thank you for letting me know!

**Comment by chenrui333** [comment]
yeah, totally, thanks!
