### ISSUE TITLE
Support for rich colored cell data

### ISSUE THREAD

**Issue by smprather** [jazzband/prettytable#252]
### Is your feature request related to a problem? Please describe.
I would like to have red/green colored PASS and FAIL elements in my table. I would like to use https://github.com/Textualize/rich markup. The coloring is working, but the column width detection is not filtering out terminal codes.

```python
from rich import print as rprint
table = prettytable.PrettyTable(field_names=("Lib", "APL Type", "P/F"))

for lib in sorted(libs_to_publish):
    for apl_type in sorted(cfg.apl_types):
        success = Path(work_dir / lib / apl_type / "DONE").exists()
        table.add_row([lib, apl_type, "[green]PASS[white]" if success else "[red]FAIL[white]"])

rprint("[white]" + table.get_string())
```
![image](https://github.com/jazzband/prettytable/assets/6503931/1a106e97-72d3-4c07-bacf-f2618a6a0d16)

### Describe alternatives you've considered
I tried using a ColorTable thinking maybe you had term-control filtering (for width calculation) enabled in there. But that didn't work with rich.print. I got all kinds of term codes just printed to my terminal as if they weren't prefixed with the [ESC] character.
![image](https://github.com/jazzband/prettytable/assets/6503931/0789ef77-dbc1-4f48-bc85-6ef047b30977)

Thanks!

**Comment by hugovk** [comment]
What's happening here, is you're passing things like `"[green]PASS[white]"` to PrettyTable, which are just strings. It's doing the width calculation based on that 18-char string.

Then you're fetching the rendered string representation of the whole table, and passing that to Rich.

Rich then converts the Rich-specific `[x]` codes into ANSI codes for printing, so `"[green]PASS[white]"` turns into a string with four visible characters, and ANSI codes on either side.

Some options:

* If using Rich colour codes, then also use Rich tables: https://rich.readthedocs.io/en/stable/tables.html
* Apply colour to the text before inserting it into the table. For example, with termcolor: https://github.com/jazzband/prettytable/issues/196#issuecomment-1240364535
* If you can get Rich to "render" `"[green]PASS[white]"` into a string with ANSI colour codes, then you could try inserting those into the table too

**Comment by smprather** [comment]
I did some experimenting. I think rich.table.Table is the way to go. Thanks!
