### ISSUE TITLE
Pretty printing inside cloudwatch logs

### ISSUE THREAD

**Issue by slidenerd** [jazzband/prettytable#255]
### Is your feature request related to a problem? Please describe.

RIght now the prettytable does not format neatly when displayed inside cloudwatch logs. 

### Describe the solution you'd like

A workaround to print the table nicely inside cloudwatch logs would be awesome

### Describe alternatives you've considered

none

### Additional context

<img width="966" alt="image" src="https://github.com/jazzband/prettytable/assets/5139030/8e8a11c4-0f2c-4000-8f98-6fcd41278e54">
table looks good inside terminal but messy inside cloudwatch logs

**Comment by hugovk** [comment]
I'm not sure how much sense it is to output a table in line-based logging, given that the cloudwatch viewer seems to be squashing multiple spaces into one, which PrettyTable has no control over.

One thing you could do is avoid ANSI colouring the text, that would skip the `0;32;` etc codes.
