### ISSUE TITLE
Colortable with title leads to broken layout

### ISSUE THREAD

**Issue by stuertz** [jazzband/prettytable#290]
### What did you do?
printed a colortable with a title

### What did you expect to happen?
normal layout as with a prettytable, but colored

### What actually happened?
title line explodes in width and one escape sequence was also printed

### What versions are you using?

* OS:  macos
* Python:  3.12
* PrettyTable:  3.10.0

```python
from prettytable import colortable

table = colortable.ColorTable(
    ("A", "B", "C", "D", "E", "f"),
    align="l",
    theme=colortable.Themes.OCEAN,
)
table.title = "Efforts"
table.add_row([1, 2, 3, 4, 5, 6])
print(table)
```

Creates (colored):
```console
+-----------------------+
|                                                                                                                                                                                       Efforts                                                                                                                                                                                       |
+[36m+---+---+---+---+---+---++
| A | B | C | D | E | f |
+---+---+---+---+---+---+
| 1 | 2 | 3 | 4 | 5 | 6 |
+---+---+---+---+---+---+
```

**Comment by hugovk** [comment]
@BD103 Please could you have a look at this?

**Comment by BD103** [comment]
My apologies, but I have not contributed in 3 years and do not use Python anymore. If someone else wants to take a look at this, please feel free!

**Comment by hugovk** [comment]
That's okay, thanks anyway!

**Comment by av-guy** [comment]
@hugovk 

I can take a look at this

**Comment by av-guy** [comment]
@hugovk 

I found the source of the issue, and I am working on a fix to the problem. I will post the details in my pull request.

**Comment by av-guy** [comment]
@hugovk

Please see https://github.com/jazzband/prettytable/pull/299 for fixes and explanation.
