### ISSUE TITLE
Print table failed when I created a copy.py in the same directory with my other python files.

### ISSUE THREAD

**Issue by TobisLee** [jazzband/prettytable#292]
### What did you do?
I create two files: main.py and copy.py. In main.py, I use the PrettyTable to print some data, and in copy.py  I copy some data from my disk.

### What did you expect to happen?
Data will be printed in terminal.

### What actually happened?
Data print failed. And I got an error: `AttributeError: module 'copy' has no attribute 'deepcopy'`

### What versions are you using?

* OS: Archlinux 6.7.9
* Python: 3.11.8
* PrettyTable: 3.10.0

Please include **code** that reproduces the issue.

1. Create a file named main.py
2. Copy the code to main.py
3. Create an empty file named copy.py
4. Run main.py

```python
from prettytable import PrettyTable

table = PrettyTable()

table.field_names = ["City name", "Area", "Population", "Annual Rainfall"]
table.add_row(["Adelaide", 1295, 1158259, 600.5])
table.add_row(["Brisbane", 5905, 1857594, 1146.4])

print(table)
```

**Comment by hugovk** [comment]
> Create an empty file named copy.py

Don't name your own files after standard library modules or you'll get errors like this. Name it something else.

https://stackoverflow.com/a/52176340/724176
