### ISSUE TITLE
Cannot release from Jazzband to PyPI

### ISSUE THREAD

**Issue by hugovk** [jazzband/prettytable#298]
I made the https://github.com/jazzband/prettytable/releases/tag/3.10.1 release, the files built on the CI, and used these dependencies:

> Successfully installed Pygments-2.17.2 SecretStorage-3.3.3 build-1.2.1 certifi-2024.2.2 cffi-1.16.0 charset-normalizer-3.3.2 cryptography-42.0.5 docutils-0.21 idna-3.6 importlib-metadata-7.1.0 jaraco.classes-3.4.0 jaraco.context-5.3.0 jaraco.functools-4.0.0 jeepney-0.8.0 keyring-25.1.0 markdown-it-py-3.0.0 mdurl-0.1.2 more-itertools-10.2.0 nh3-0.2.17 packaging-24.0 pkginfo-1.10.0 pycparser-2.22 pyproject_hooks-1.0.0 readme-renderer-43.0 requests-2.31.0 requests-toolbelt-1.0.0 rfc3986-2.0.0 rich-13.7.1 twine-5.0.0 urllib3-2.2.1 wheel-0.43.0 zipp-3.18.1

https://github.com/jazzband/prettytable/actions/runs/8620807257/job/23628373166

And they uploaded to the Jazzband staging area okay, but trying to upload to from there to PyPI failed:

> Uploading distributions to https://upload.pypi.org/legacy/ [31mERROR [0m InvalidDistribution: Metadata is missing required fields: Name, Version. Make sure the distribution includes the files where those fields are specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2, 2.0, 2.1, 2.2.

https://jazzband.co/projects/prettytable/upload/1195/release

Need to check what's missing...

**Comment by hugovk** [comment]
It's due to outdated dependencies on the Jazzband website, reported at https://github.com/jazzband/help/issues/360.

**Comment by 0xalpharush** [comment]
Any idea when the latest release will get published to PyPI?

**Comment by hugovk** [comment]
Sorry no, we're blocked by https://github.com/jazzband/help/issues/360.

**Comment by jezdez** [comment]
This should be unblocked again, could you try again @hugovk?

**Comment by hugovk** [comment]
It's working now, thank you very much!
