### ISSUE TITLE
New color themes?

### ISSUE THREAD

**Issue by Bikes4Fun** [jazzband/prettytable#310]
This request adds new color themes to the ColorTable class in PrettyTable. This provides users with built in options for customizing the appearance of their tables.

Changes made:
- Added 8 new themes to the `Themes` class in `colortable.py`:
  - FOREST
  - SUNSET
  - OCEAN_DEEP
  - LAVENDER
  - MONOCHROME
  - NEON
  - EARTH
  - PASTEL

Benefits:
1. Increased customization options for users
2. More variety in color schemes to suit different preferences and use cases
3. Includes themes with both basic and extended color palettes for compatibility with various terminal environments

Testing:
- Tested all new themes in multiple terminal environments to ensure compatibility
- Verified that existing functionality remains unchanged

Usage example:
<img width="459" alt="Screenshot 2024-09-22 at 11 17 24 PM" src="https://github.com/user-attachments/assets/e75e6c74-4380-4d92-a808-98a9b312c491">
<img width="471" alt="Screenshot 2024-09-22 at 11 17 33 PM" src="https://github.com/user-attachments/assets/77d47751-3df0-44d6-8e5e-8f3edec8d84d">
<img width="473" alt="Screenshot 2024-09-22 at 11 17 41 PM" src="https://github.com/user-attachments/assets/64e5265e-edac-4419-92c0-4998ff4a83a1">

**Comment by hugovk** [comment]
Looks good, would you like to open a PR?

**Comment by Bikes4Fun** [comment]
Yes please :)

**Comment by Bikes4Fun** [comment]
Hi, I've worked on team projects but I have not contributed to open source public projects yet. I have this working locally but in the past I've had a button to branch from an issue. Could you possibly direct me to that system for a managed project like this?

**Comment by hugovk** [comment]
Hi, here's some info on how to contribute to a project on GitHub, does this help?

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by Bikes4Fun** [comment]
Oh yes. That is a little different. Thank you so much.
